title: 알뜰 쇼핑 천국
description: '최고의 가격으로 스마트한 쇼핑을 경험하세요!'
url: 'https://ttusigi575.github.io'
baseurl: ''

# title: Your awesome title
# email: your-email@example.com
# url: "" # the base hostname & protocol for your site, e.g. http://example.com

author:
  name: 'Smart Shopping Hub'
  email: snlee6999@gmail.com.com
  twitter_username:
  facebook_username: 
  github_username: 
  linkedin_username: 
  
# Build settings
destination: _site
paginate: 50
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

# theme: minima
plugins:
  - jekyll-feed

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
