# Site settings
title: 알뜰 쇼핑 천국
description: '최고의 가격으로 스마트한 쇼핑을 경험하세요!'
url: 'https://ttusigi575.github.io'
baseurl: ''
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'
# disable_landing_page: true
# timezone: Asia/Seoul

author:
  name: 'Smart Shopping Hub'
  email: snlee6999@gmail.com.com
  twitter_username:
  facebook_username: 
  github_username: 
  linkedin_username: 

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 50
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']

